// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq_0y-ZYLE1QYXTd94ZaRJPe8Pio8lIjk',
    appId: '1:804050289685:web:b4083cfcedf51524a8ba1c',
    messagingSenderId: '804050289685',
    projectId: 'share-a-bite-sih23',
    authDomain: 'share-a-bite-sih23.firebaseapp.com',
    storageBucket: 'share-a-bite-sih23.appspot.com',
    measurementId: 'G-4QY1V9YGH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7a6s7g297OCXwZXECG3KU77TCTYb9-3U',
    appId: '1:804050289685:android:cefc643490570ac8a8ba1c',
    messagingSenderId: '804050289685',
    projectId: 'share-a-bite-sih23',
    storageBucket: 'share-a-bite-sih23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqDTsOBFrB0HlrqpiF0a8eQuP36GWLP-8',
    appId: '1:804050289685:ios:1c7f8dc29b9e24d2a8ba1c',
    messagingSenderId: '804050289685',
    projectId: 'share-a-bite-sih23',
    storageBucket: 'share-a-bite-sih23.appspot.com',
    iosClientId: '804050289685-9a2n4bp8doqpu9n77hjsfu28rftmm8bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareABite',
  );
}
